
Process PoolWorker-27:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
Process PoolWorker-22:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
Process PoolWorker-25:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
Process PoolWorker-21:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
Process PoolWorker-30:
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
Process PoolWorker-29:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
Process PoolWorker-24:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
Process PoolWorker-28:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
Process PoolWorker-23:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
Process PoolWorker-26:
Traceback (most recent call last):
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jpz5181/anaconda2/lib/python2.7/multiprocessing/pool.py", line 122, in worker
    put((job, i, (False, wrapped)))
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 383, in put
    return send(obj)
  File "/home/jpz5181/anaconda2/lib/python2.7/site-packages/joblib/pool.py", line 369, in send
    self._writer.send_bytes(buffer.getvalue())
IOError: [Errno 32] Broken pipe
